services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./minischoolback
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydb
    ports:
      - "3000:5000"
    depends_on:
      - db
  frontend:
    build: ./minischoolfront
    ports:
      - "3000:3000"
    environment:
      API_URL: http://backend:5000 # http://192.168.0.3:5000    
      depends_on:
      - backend
volumes:
  postgres_data: