FROM ubuntu:latest
## Basic mirror update
RUN apt update
## install dependencies
RUN apt install gcc, g++, core-utils

## install main program
RUN apt install postgres

## RUN MAIN PROGRAM

CMD ["POSTGRESQL"]